### ISSUE TITLE
Errors in latest install or USRP_Client in DVSwitch

### ISSUE THREAD

**Issue by f5vmr** [DVSwitch/USRP_Client#7]
Having installed all the ancillary items to a running DVSwitch/SVXReflector, on starting the pyUC.py I am getting the following errors.
Running with python pyUC.py I get...
SyntaxError: Non-ASCII character '\xe2' in file pyUC.py on line 206, but no encoding declared;
Running it with python3 pyUC.py i get...
Traceback (most recent call last):
  File "pyUC.py", line 1542, in <module>
    root = Tk()
  File "/usr/lib/python3.7/tkinter/__init__.py", line 2023, in __init__
    self.tk = _tkinter.create(screenName, baseName, className, interactive, wantobjects, useTk, sync, use)
_tkinter.TclError: no display name and no $DISPLAY environment variable
Everything has been set in the pyUC.ini as I require.

As an added complication the same device is running SVXPortal (sa2blv), svxreflector, and DVSwitch with Analog_Bridge, MMDVM_Bridge with md380-emu, on a Raspberry Pi 3 and it's fast and cool in temperature. The USRP_Client is the final part of the puzzle and is not currently working. Analog_Bridge is receiving data from MMDVM_Bridge.

**Comment by MrBungle42** [comment]
pyUC runs as a GUI application on the PI desktop window manager.  Do you
have a desktop installed, or is this a headless system?
If it is headless, then I recommend you use Analog_Reflector which will
allow you to render the application on your PC with a simple browser.

**Comment by f5vmr** [comment]
This is a headless system. I have everything running, including Analog_Bridge. I am just verifying that the SVXReflector build is up to date, as DL1HRC has made some changes recently.

What is this Analog_Reflector of which you speak……? It is certainly nothing I have heard mentioned before.

This is a Buster Build on a Raspberry Pi 3. The only Dashboard elements are on PHP all running concurrently.

DVSwitch, SVXReflector SVXPortal are all running on the same device.

**Comment by MrBungle42** [comment]
Join us here:
https://dvswitch.groups.io/g/main
